const Categories = {
  ANY_CATEGORY: { value: 'any', title: 'Any Category' },
  GENERAL_KNOWLEDGE: { value: 9, title: 'General Knowledge' },
  ENTERTAINMENT_BOOKS: { value: 10, title: 'Entertainment: Books' },
  ENTERTAINMENT_FILM: { value: 11, title: 'Entertainment: Film' },
  ENTERTAINMENT_MUSIC: { value: 12, title: 'Entertainment: Music' },
  ENTERTAINMENT_MUSICALS: { value: 13, title: 'Entertainment: Musicals' },
  ENTERTAINMENT_TELEVISION: { value: 14, title: 'Entertainment: Television' },
  ENTERTAINMENT_VIDEO_GAMES: { value: 15, title: 'Entertainment: Video Games' },
  ENTERTAINMENT_BOARD_GAMES: { value: 16, title: 'Entertainment: Board Games' },
  SCIENCE_AND_NATURE: { value: 17, title: 'Science and Nature' },
  SCIENCE_COMPUTERS: { value: 18, title: 'Science: Computers' },
  SCIENCE_MATHEMATICS: { value: 19, title: 'Science: Mathematics' },
  MYTHOLOGY: { value: 20, title: 'Mythology' },
  SPORTS: { value: 21, title: 'Sports' },
  GEOGRAPHY: { value: 22, title: 'Geography' },
  HISTORY: { value: 23, title: 'History' },
  POLITICS: { value: 24, title: 'Politics' },
  ART: { value: 25, title: 'Art' },
  CELEBRITIES: { value: 26, title: 'Celebrities' },
  ANIMALS: { value: 27, title: 'Animals' },
  VEHICLES: { value: 28, title: 'Vehicles' },
  ENTERTAINMENT_COMICS: { value: 29, title: 'Entertainment: Comics' },
  SCIENCE_GADGETS: { value: 30, title: 'Science: Gadgets' },
  ENTERTAINMENT_JAPANESE_ANIME_AND_MANGA: { value: 31, title: 'Entertainment: Japanese Anime and Manga' },
  ENTERTAINMENT_CARTOON_ANIMATIONS: { value: 32, title: 'Entertainment: Cartoon and Animations' },
};

export default Categories;
